# Generated by Django 3.2.9 on 2021-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=None, max_length=150)),
                ('TitleID', models.CharField(default=None, max_length=150)),
                ('Link', models.CharField(default=None, max_length=150)),
                ('PubYear', models.IntegerField(default=None)),
                ('DownloadLink', models.CharField(default=None, max_length=150, null=True)),
                ('DateAdded', models.CharField(default=None, max_length=150)),
                ('Category', models.CharField(default=None, max_length=150)),
                ('UserID', models.CharField(default=None, max_length=150)),
            ],
        ),
    ]
