# Generated by Django 3.2.9 on 2021-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_researcharchive_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharchive',
            name='Abstract',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='researcharchive',
            name='Author',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='researcharchive',
            name='Citations',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
