# Generated by Django 3.2.9 on 2021-12-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20211219_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcharchive',
            name='DownloadLink',
        ),
        migrations.AlterField(
            model_name='researcharchive',
            name='Author',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
